import type { PortfolioContent } from './types';

export const englishPortfolio: PortfolioContent = {
  metrics: [
    {
      value: '40 cities',
      label: 'in one nationwide program',
      note: '2026 AI+X Creation Festival',
    },
    {
      value: 'Nearly 1,000',
      label: 'developers reached',
      note: 'StepFun four-city series',
    },
    {
      value: '31 + 44',
      label: 'agents and automations',
      note: 'Documented in 2026',
    },
    {
      value: 'Since 2019',
      label: 'community practice',
      note: 'From learner to city ecosystem lead',
    },
  ],
  work: [
    {
      id: 'wechat-innovation-workshop',
      category: 'conference',
      title: 'WeChat Developer Innovation Workshop',
      year: '2026',
      location: 'Chengdu · Shanghai',
      role: 'Program lead',
      summary: 'A developer workshop organized with WeChat Mini Programs in Chengdu and Shanghai. I led the program and worked with the team to plan the content, invite developers, and organize both sessions.',
      result: 'Around 100 participants per workshop',
      image: '/images/work/03.jpg',
      imageAlt: 'Developers and organizers at the WeChat Developer Innovation Workshop in Chengdu',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'This was a two-city developer program organized with WeChat Mini Programs. The aim was to give developers useful content and a setting where they could exchange ideas with peers.',
        responsibilities: ['Kept the two-city program moving on one shared timeline', 'Co-designed the workshop content with the team', 'Invited developers and organized the Chengdu and Shanghai sessions'],
        outcome: 'Both workshops took place, with around 100 participants at each session.',
        reflection: 'A useful developer event starts by defining what participants should leave with, then choosing the content and scale that support that outcome.',
      },
    },
    {
      id: 'superai-china',
      category: 'global',
      title: 'SuperAI’s China visit',
      year: '2026',
      location: 'Hangzhou · Shanghai · Singapore',
      role: 'Ecosystem partner and local liaison',
      summary: 'I accompanied the SuperAI team through universities, open-source communities, and AI companies in Hangzhou and Shanghai, then represented Datawhale at their conference in Singapore.',
      result: 'Visits and exchanges in Hangzhou, Shanghai, and Singapore',
      image: '/blog/superai-china/team.jpg',
      imageAlt: 'Darren with the SuperAI ecosystem team and China AI community partners',
      imageClassName: 'object-cover object-center',
      noteHref: '/blog/superai-china-ecosystem-visit',
      caseStudy: {
        context: 'The SuperAI team wanted to learn about China’s AI ecosystem. Planning the visits meant understanding each side’s background and the questions they wanted to discuss.',
        responsibilities: ['Helped shape the visit across Hangzhou and Shanghai', 'Connected the team with universities, open-source communities, and AI companies', 'Joined the conversations, then represented Datawhale at SuperAI in Singapore'],
        outcome: 'The Hangzhou and Shanghai visits included Zhejiang University, ModelScope, Qwen, and MiniMax. I published a field note with five observations from the exchange, then represented Datawhale at SuperAI in Singapore.',
        reflection: 'Understanding what each side wants to learn makes it easier to continue the conversation after a visit.',
        materials: [
          {
            type: 'Field note · 2026',
            title: 'Five Observations from Accompanying the SuperAI Team in Hangzhou and Shanghai',
            description: 'I documented five observations from the conversations, with the visit route and a group photo. The note records what each side wanted to understand and the context needed for useful cross-border exchanges.',
            href: '/blog/superai-china-ecosystem-visit',
          },
          {
            type: 'Organizer report',
            title: 'SuperAI 2026 report and community partners',
            description: 'The organizer lists Datawhale and AGI Villa among its community partners, providing conference context. The field note above records my own work during the Hangzhou and Shanghai visits.',
            href: 'https://www.superai.com/reports/2026-event-report',
          },
        ],
      },
    },
    {
      id: 'agent-speaking',
      category: 'speaking',
      title: 'A Digital Organization with 31 Agents',
      heroSummary: 'I organized 31 agents into a working system and documented how they collaborate, where they fail, and what the experience taught me about management.',
      year: '2026',
      location: 'Technology events in China and abroad',
      role: 'Author and invited speaker',
      summary: 'After publishing my essay about working with 31 agents, I received invitations to speak. I explain how the agents divide tasks, where they fail, and how I manage the work I delegate to AI.',
      result: 'The essay led to several talks and collaboration invitations',
      image: '/blog/ai-employees/digital-organization.png',
      imageAlt: 'The digital organization diagram from Darren’s article on working with 31 agents',
      imageClassName: 'object-contain bg-[#f7f5e9] p-4',
      noteHref: '/blog/managing-31-ai-employees',
      caseStudy: {
        context: 'After an essay about my 31-agent work system was published, companies, conferences, and communities began inviting me to explain the practice in person.',
        responsibilities: ['Mapped the agents\' roles, information flow, and common failure points', 'Adapted the talk for different audiences and settings', 'Used day-to-day tasks to explain how I manage work delegated to AI'],
        outcome: 'I published an essay documenting the 31 agents, 44 automated tasks, and collaboration rules I use in daily work. It led to several talks and collaboration invitations, while the questions from those rooms helped the system keep evolving.',
        reflection: 'The most useful part of an agent talk is rarely a tool list. It is the design of how work is understood, delegated, checked, and improved.',
        materials: [
          {
            type: 'Practice essay · 2026',
            title: 'Managing 31 AI Employees Changed How I Understand Management',
            description: 'The essay includes the organization chart, agent roles, and product screenshots from that stage of the system. It explains information sharing, delegation, and review rules, alongside failed tasks and automations I disabled.',
            href: '/blog/managing-31-ai-employees',
          },
        ],
      },
    },
    {
      id: 'stepfun-four-cities',
      category: 'ecosystem',
      title: 'StepFun developer series',
      year: '2026',
      location: 'Beijing · Shanghai · Hangzhou · Shenzhen',
      role: 'Series initiator and program lead',
      summary: 'I initiated and led a four-city developer series, working with local communities to reach participants and organize the events.',
      result: 'Nearly 1,000 developers reached across four cities',
      image: '/images/work/14.jpg',
      imageAlt: 'Darren speaking at a StepFun Agent Builders Gathering',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'The developers and local partners differed in each city, while all four events needed a consistent theme and standard of organization.',
        responsibilities: ['Initiated the series and led the overall program', 'Worked with local communities in Beijing, Shanghai, Hangzhou, and Shenzhen', 'Coordinated participant outreach and event operations'],
        outcome: 'The four-city series reached nearly 1,000 developers.',
        reflection: 'A multi-city program needs a shared plan, with room for local organizers to adapt it to their own communities.',
        materials: [
          {
            type: 'Organizer recap · 2026.07.29',
            title: 'Datawhale recap of the four-city developer series',
            description: 'Datawhale documents four jointly hosted technical meetups with StepFun in Beijing, Shanghai, Shenzhen, and Hangzhou, with over 200 registrations per city. Registrations, reach, and attendance are different measures.',
            href: 'https://www.sohu.com/a/1056265438_122105141',
          },
        ],
      },
    },
    {
      id: 'aix-creation-festival',
      category: 'ecosystem',
      title: 'AI+X Creation Festival',
      heroSummary: 'I initiated the festival and worked with local organizers across 40 cities in China.',
      year: '2026',
      location: '40 cities across China',
      role: 'Initiator and program lead',
      summary: 'I initiated the AI+X Creation Festival and worked with local organizers to bring it to 40 cities, so AI learners and developers could meet and build where they lived rather than having to travel to a major hub.',
      result: 'A coordinated program across 40 cities',
      image: '/images/work/aix-creation-festival.jpg',
      imageAlt: 'Participants at an OPC workshop during the AI+X Creation Festival',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'Many AI learners and developers live outside the largest technology hubs. They still need local opportunities to meet, exchange ideas, and build together.',
        responsibilities: ['Initiated the AI+X Creation Festival and agreed on a shared plan', 'Worked with local organizers to move each city forward', 'Coordinated one nationwide program across 40 cities'],
        outcome: 'Local events took place in 40 cities during the same period.',
        reflection: 'Across 40 cities, organizers need a shared purpose and room to adapt events to local needs.',
      },
    },
    {
      id: 'waic-pioneers-night',
      category: 'conference',
      title: "WAIC AI Pioneers' Night",
      year: '2026',
      location: 'Shanghai',
      role: 'Co-initiator and program lead',
      summary: 'I organized this official WAIC evening event with WAIC UP MORE and Alibaba Cloud. I led program planning, invited speakers, and ran the on-site program.',
      result: 'Around 100 AI developers, founders, and ecosystem partners attended',
      image: '/images/work/01-cover.png',
      imageAlt: "Darren opening WAIC AI Pioneers' Night",
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'This official WAIC evening event, organized with WAIC UP MORE and Alibaba Cloud, created a smaller setting for deeper conversation during a large conference week.',
        responsibilities: ['Co-initiated the event and led the overall program', 'Shaped the content and invited speakers', 'Coordinated the event on the night'],
        outcome: 'Around 100 AI developers, founders, and ecosystem partners attended.',
        reflection: 'An evening event needs time outside the agenda so participants can continue discussing the questions that matter to them.',
      },
    },
    {
      id: 'rumata-workshop',
      category: 'global',
      title: 'Rumata Product Co-creation Workshop',
      heroSummary: 'I brought founders and potential users together to try the product and share early feedback.',
      year: '2026',
      location: 'China',
      role: 'Initiator and program lead',
      summary: 'I invited Israeli AI founders Nitzan and Yoel to China for a small product workshop. They sat down directly with developers and potential users and heard what people thought after trying the product.',
      result: 'Around 50 participants; first round of product feedback collected',
      image: '/images/work/05.jpg',
      imageAlt: 'Participants at the Rumata Startup Co-creation product workshop',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'Israeli AI founders Nitzan and Yoel wanted to understand how developers and potential users in China would use Rumata. The workshop gave them a chance to hear directly from people trying the product.',
        responsibilities: ['Invited Nitzan and Yoel to China and clarified what this round needed to test with the founders', 'Brought together developers and potential users around hands-on product use', 'Designed a workshop around trying the product, asking questions, and sharing feedback directly with the founders'],
        outcome: 'Around 50 people joined the workshop. Developers and potential users tried the product and spoke directly with its founders, completing the team’s first round of product feedback collection.',
        outcomeNote: 'This record covers hands-on use and initial feedback collection. Follow-up product changes and usage outcomes are not yet documented here.',
        reflection: 'For this kind of workshop, I start with what the team wants to test before deciding whom to invite. Time spent using the product helps founders hear how people understand it and where they need an explanation. The value of that feedback still depends on the team’s subsequent decisions and actions.',
      },
    },
    {
      id: 'datawhale-city-ecosystem',
      category: 'ecosystem',
      title: 'Datawhale city and developer ecosystem',
      year: '2019—present',
      location: 'Cities across China',
      role: 'City ecosystem lead',
      summary: 'I joined Datawhale in 2019 and gradually took responsibility for its city ecosystem work. Since then, I have worked with learners, developers, universities, open-source contributors, and local organizers across China.',
      result: 'Multiple city programs and nationwide collaborations',
      image: '/images/work/12.jpg',
      imageAlt: 'Developers at a Datawhale OpenClaw city event',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: 'I joined Datawhale in 2019 to learn AI and gradually took on more work with city communities and developers.',
        responsibilities: ['Connected learners, developers, universities, and open-source contributors', 'Worked with local organizers to deliver city events', 'Helped move multiple nationwide collaborations forward'],
        outcome: 'I continued contributing to city programs and nationwide projects, gradually taking responsibility for the city ecosystem.',
        reflection: 'A community needs ongoing care. Trust grows as its members keep learning and working together.',
        materials: [
          {
            type: 'Open-source project record',
            title: 'Vector Search and RAG: public project credits',
            description: 'The official Datawhale repository lists me as project lead and links to my GitHub profile, documenting one specific open-source content collaboration.',
            href: 'https://github.com/datawhalechina/what-is-vs#贡献者名单',
          },
        ],
      },
    },
  ],
  collaborations: [
    {
      id: 'developer-events',
      number: '01',
      title: 'Developer events and ecosystem programs',
      bestFor: 'Teams planning a developer event, multi-city series, or conference partnership',
      description: 'I have led single-city workshops, a four-city series, an official WAIC evening event, and a 40-city national program. I can help with planning, speaker invitations, running the event, and documenting it afterward, depending on what the team needs.',
      outcomes: ['Agree on the event’s purpose, participants, and content', 'Invite speakers, developers, and partners', 'Run the event and document what happened'],
      invitation: 'Planning a developer event or ecosystem program?',
      linkLabel: 'Explore event and ecosystem collaborations',
      inquiry: ['A short introduction to your team or project', 'Whom you want to reach and what you want to achieve', 'Approximate timing, city, and scale'],
    },
    {
      id: 'product-workshops',
      number: '02',
      title: 'Early-user workshops for AI products',
      bestFor: 'AI teams with a usable product seeking early feedback or conversations with developers in China',
      description: 'When the product is ready to try, I can organize a small workshop with developers and potential users so the team can hear their feedback directly.',
      outcomes: ['Agree on what this round of product testing should answer', 'Invite developers willing to try the product', 'Document the feedback to help the team decide what to do next'],
      invitation: 'Planning a hands-on product workshop?',
      linkLabel: 'Explore a product workshop',
      inquiry: ['A product link and the version people can try', 'The main question you want this round to answer', 'Approximate timing and the users you hope to invite'],
    },
    {
      id: 'ai-talks',
      number: '03',
      title: 'AI and agent talks',
      bestFor: 'Companies, conferences, universities, and developer communities',
      description: 'I share lessons from using AI, building agents, and managing a multi-agent system in my daily work: how I divide tasks, check results, and deal with things going wrong.',
      outcomes: ['Keynotes or panel conversations', 'Private sessions for teams', 'Hands-on workshops using day-to-day work tasks'],
      invitation: 'Would an AI or agent talk be useful for your team?',
      linkLabel: 'Explore AI and agent talks',
      inquiry: ['A short introduction to your event or team', 'The audience’s background and main questions', 'Approximate timing and session format'],
    },
  ],
};
