import type { PortfolioContent } from './types';

export const chinesePortfolio: PortfolioContent = {
  metrics: [
    {
      value: '40 城',
      label: '全国联动',
      note: '2026 AI+X 创造节',
    },
    {
      value: '近 1,000',
      label: '接触到的开发者',
      note: '阶跃星辰四城系列活动',
    },
    {
      value: '31 + 44',
      label: 'Agent 和自动任务',
      note: '2026 年实践记录',
    },
    {
      value: '2019—',
      label: '长期社区实践',
      note: '从学习者到城市生态负责人',
    },
  ],
  work: [
    {
      id: 'wechat-innovation-workshop',
      category: 'conference',
      title: '微信开发者创新工坊',
      year: '2026',
      location: '成都 · 上海',
      role: '项目负责人',
      summary: '与微信小程序在成都和上海联合组织开发者创新工坊。我负责项目推进，也和团队一起策划内容、邀请开发者，并组织两地活动。',
      result: '单场约 100 人参与',
      image: '/images/work/03.jpg',
      imageAlt: '微信开发者创新工坊成都现场，开发者与组织团队合影',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '这是一个与微信小程序联合推进的两城开发者项目。目标是让开发者在现场获得有用的内容，也能和同行交流。',
        responsibilities: ['协调项目进度与两地协作', '与团队一起策划活动内容', '邀请开发者，组织成都和上海两场活动'],
        outcome: '成都和上海两场工坊均已举办，单场约 100 人参与。',
        reflection: '一场有用的开发者活动，应该先把参与者要带走什么说清楚，再决定内容与规模。',
      },
    },
    {
      id: 'superai-china',
      category: 'global',
      title: 'SuperAI 中国 AI 生态走访',
      year: '2026',
      location: '杭州 · 上海 · 新加坡',
      role: '生态伙伴、走访协调与陪同',
      summary: '陪同 SuperAI 团队在杭州和上海走访高校、开源社区与 AI 公司，后来也代表 Datawhale 参加了他们在新加坡的大会。',
      result: '完成杭州、上海和新加坡三地交流',
      image: '/blog/superai-china/team.jpg',
      imageAlt: 'Darren 与 SuperAI 生态团队及中国 AI 社区伙伴合影',
      imageClassName: 'object-cover object-center',
      noteHref: '/blog/superai-china-ecosystem-visit',
      caseStudy: {
        context: 'SuperAI 团队希望了解中国 AI 生态。安排走访时，需要了解双方的背景和关心的问题。',
        responsibilities: ['协助安排杭州与上海的走访行程', '协助联系高校、开源社区与 AI 公司', '陪同交流，后续代表 Datawhale 前往新加坡参会'],
        outcome: '杭州与上海的走访覆盖浙大、魔搭社区、Qwen、MiniMax 等高校、社区与 AI 团队。我将交流中的五个现场观察整理成公开手记，后来代表 Datawhale 参加了新加坡的 SuperAI 大会。',
        reflection: '了解双方各自想解决的问题，才更容易在走访之后继续交流。',
        materials: [
          {
            type: '现场手记 · 2026',
            title: '陪 SuperAI 团队走访杭州和上海后，我记下了五个现场观察',
            description: '我把陪同走访中的交流整理成五个观察，附上走访路线与现场合影，记录双方关心的问题，以及跨境生态交流需要补足的背景。',
            href: '/blog/superai-china-ecosystem-visit',
          },
          {
            type: '主办方报告',
            title: 'SuperAI 2026 大会报告与社区伙伴',
            description: '主办方报告将 Datawhale 和 AGI Villa 列为社区伙伴，介绍大会与社区交流的背景。杭州、上海走访中的个人工作记录在上方手记中。',
            href: 'https://www.superai.com/reports/2026-event-report',
          },
        ],
      },
    },
    {
      id: 'agent-speaking',
      category: 'speaking',
      title: '31 个 Agent 的数字组织实践',
      heroSummary: '我把日常运行的 31 个 Agent 组织成一个工作系统，记录它们怎样协作、哪里会出错，以及我怎样重新理解管理。',
      year: '2026',
      location: '中国及海外科技活动',
      role: '作者、分享嘉宾',
      summary: '关于 31 个 Agent 的文章发布后，我陆续收到分享邀请。我会讲这些 Agent 怎样分工、哪里会出错，以及把任务交给 AI 后，我怎样调整自己的管理方式。',
      result: '文章发布后，陆续带来多次分享与合作邀请',
      image: '/blog/ai-employees/digital-organization.png',
      imageAlt: '31 个 Agent 实践文章中的数字组织结构图',
      imageClassName: 'object-contain bg-[#f7f5e9] p-4',
      noteHref: '/blog/managing-31-ai-employees',
      caseStudy: {
        context: '一篇关于 31 个 Agent 工作系统的文章发布后，不同的企业、大会与社区开始邀请我把这套实践讲清楚。',
        responsibilities: ['说明 Agent 如何分工、同步信息，以及哪些环节容易出错', '根据不同听众调整分享结构', '结合日常任务，说明把工作交给 AI 后怎样管理'],
        outcome: '我把日常使用的 31 个 Agent、44 个自动任务及协作规则整理成公开长文。文章带来多次分享与合作邀请，也让这套工作系统在交流中继续迭代。',
        reflection: '对 Agent 的分享最有价值的部分，往往不是工具清单，而是任务怎样被理解、授权和检查。',
        materials: [
          {
            type: '实践长文 · 2026',
            title: '管了 31 个 AI 员工之后，我重新理解了管理学',
            description: '文中保留了当时的组织结构、Agent 分工和产品界面，具体记录信息同步、授权与检查规则，也写下任务失败和停用的经历。',
            href: '/blog/managing-31-ai-employees',
          },
        ],
      },
    },
    {
      id: 'stepfun-four-cities',
      category: 'ecosystem',
      title: '阶跃星辰开发者系列活动',
      year: '2026',
      location: '北京 · 上海 · 杭州 · 深圳',
      role: '系列活动发起与负责人',
      summary: '在北京、上海、杭州和深圳组织四场开发者活动。我负责系列策划和整体推进，并与各地社区一起完成招募和现场执行。',
      result: '四城触达近 1,000 位开发者',
      image: '/images/work/14.jpg',
      imageAlt: 'Darren 在阶跃星辰 Agent Builders Gathering 现场分享',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '四座城市的开发者群体与合作社区各不相同，但整个系列需要保持一致的主题与质量。',
        responsibilities: ['发起四城系列并负责整体策划', '与北京、上海、杭州、深圳当地社区协作', '推进参与者招募与现场执行'],
        outcome: '四场活动共触达近 1,000 位开发者。',
        reflection: '多城项目需要共同的目标和安排，也要让当地组织者根据各自社区的情况调整。',
        materials: [
          {
            type: '组织者复盘 · 2026.07.29',
            title: 'Datawhale 四城开发者活动复盘',
            description: 'Datawhale 的复盘记录了与阶跃星辰在北京、上海、深圳和杭州联合举办的四场技术沙龙，以及每城单场超过 200 人的报名情况。这里的报名数与触达、实际到场人数采用不同口径。',
            href: 'https://www.sohu.com/a/1056265438_122105141',
          },
        ],
      },
    },
    {
      id: 'aix-creation-festival',
      category: 'ecosystem',
      title: 'AI+X 创造节',
      heroSummary: '我发起创造节，与各地组织者一起在全国 40 座城市举办活动。',
      year: '2026',
      location: '全国 40 城',
      role: '发起人、项目负责人',
      summary: '我发起 AI+X 创造节，并和各地组织者一起在 40 座城市举办活动。我们希望各地的 AI 学习者和开发者，可以在自己的城市见面、交流和动手做东西。',
      result: '40 座城市同步参与',
      image: '/images/work/aix-creation-festival.jpg',
      imageAlt: 'AI+X 创造节 OPC 能力专场的现场合影',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '很多 AI 学习者和开发者不在一线城市，但他们同样需要在本地见面、交流和动手创作的机会。',
        responsibilities: ['发起 AI+X 创造节，确定共同的项目安排', '与各地组织者协作推进', '协调 40 座城市的活动安排'],
        outcome: '全国 40 座城市在同一时期开展了活动。',
        reflection: '40 座城市有共同的目标，各地组织者也需要根据当地情况安排活动。',
      },
    },
    {
      id: 'waic-pioneers-night',
      category: 'conference',
      title: "WAIC AI Pioneers' Night",
      year: '2026',
      location: '上海',
      role: '联合发起、项目负责人',
      summary: '我与 WAIC UP MORE、阿里云共同组织 WAIC 官方夜场，负责项目推进、嘉宾邀请和活动内容。',
      result: '约 100 位 AI 开发者、创业者与生态伙伴到场',
      image: '/images/work/01-cover.png',
      imageAlt: "Darren 在 WAIC AI Pioneers' Night 现场开场分享",
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '这场 WAIC 官方夜场由 WAIC UP MORE、阿里云与我们共同组织，希望参会者在大会期间有机会在晚间进一步交流。',
        responsibilities: ['共同发起并推进整体项目', '策划活动内容、邀请嘉宾', '协调活动当晚的执行'],
        outcome: '约 100 位 AI 开发者、创业者与生态伙伴到场。',
        reflection: '夜场的议程需要留出交流时间，让参与者有机会把关心的问题聊下去。',
      },
    },
    {
      id: 'rumata-workshop',
      category: 'global',
      title: 'Rumata 产品共创 Workshop',
      heroSummary: '我组织产品体验和交流，让创始人听到开发者的第一轮反馈。',
      year: '2026',
      location: '中国',
      role: '发起人、项目负责人',
      summary: '我邀请以色列 AI 创业者 Nitzan 和 Yoel 来中国。我们组织了一场小型产品 Workshop，让他们直接和开发者及潜在用户坐在一起，听大家实际使用产品之后怎么说。',
      result: '约 50 人参与，完成第一轮产品反馈',
      image: '/images/work/05.jpg',
      imageAlt: 'Rumata Startup Co-creation 产品工作坊现场合影',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '以色列 AI 创业者 Nitzan 和 Yoel 希望了解中国开发者与潜在用户怎样使用 Rumata。这次 Workshop 希望让他们直接听到试用反馈。',
        responsibilities: ['邀请 Nitzan 和 Yoel 来中国，并与创始人确认这一轮的测试目标', '邀请愿意试用产品的开发者和潜在用户', '安排产品体验、提问与反馈，让创始人直接听取使用感受'],
        outcome: '约 50 人参与 Workshop。开发者与潜在用户实际体验了产品，并与创始人面对面交流，团队完成了第一轮产品反馈收集。',
        outcomeNote: '这份记录只包括产品体验和首轮反馈，暂未记录后续的产品调整与使用情况。',
        reflection: '设计这类 Workshop 时，我会先确认团队想验证什么，再考虑邀请谁。把时间留给实际使用，创始人才能听见用户怎样理解产品、在哪里需要解释；这些反馈的价值，需要由团队后续的判断和行动继续验证。',
      },
    },
    {
      id: 'datawhale-city-ecosystem',
      category: 'ecosystem',
      title: 'Datawhale 城市与开发者生态',
      year: '2019—至今',
      location: '中国多城市',
      role: '城市生态负责人',
      summary: '从 2019 年开始参与 Datawhale，后来逐渐负责城市生态工作。日常会接触学习者、开发者、高校、开源贡献者和各地组织者。',
      result: '参与并推动多次城市活动与全国联动项目',
      image: '/images/work/12.jpg',
      imageAlt: 'Datawhale OpenClaw 城市开发者活动现场合影',
      imageClassName: 'object-cover object-center',
      caseStudy: {
        context: '从 2019 年的普通学习者开始，这项工作逐渐变成一项长期的城市与开发者生态实践。',
        responsibilities: ['连接学习者、开发者、高校与开源贡献者', '与各地组织者协作完成城市活动', '参与并推动多次全国联动项目'],
        outcome: '持续参与城市活动与全国项目，并逐渐承担城市生态责任。',
        reflection: '社区需要持续维护。成员之间的信任，来自一次次一起学习和做事的经历。',
        materials: [
          {
            type: '开源项目记录',
            title: '《向量检索与 RAG 实践》贡献名单',
            description: 'Datawhale 官方仓库将我列为项目负责人，并链接到我的 GitHub 账号。这份记录呈现了我参与的一项具体开源内容协作。',
            href: 'https://github.com/datawhalechina/what-is-vs#贡献者名单',
          },
        ],
      },
    },
  ],
  collaborations: [
    {
      id: 'developer-events',
      number: '01',
      title: '开发者活动与生态项目',
      bestFor: '准备组织开发者活动、多城市联动或大会合作的团队',
      description: '我做过单城 Workshop、四城系列活动，也负责过 WAIC 官方夜场和 40 城全国联动。合作可以从活动策划开始，再根据需要安排嘉宾邀请、活动执行和后续内容整理。',
      outcomes: ['确定活动目标、参与者和内容安排', '邀请嘉宾、开发者与合作伙伴', '组织活动，并整理活动后的内容记录'],
      invitation: '你也在筹备开发者活动或生态项目？',
      linkLabel: '了解活动与生态合作',
      inquiry: ['团队或项目的简单介绍', '希望邀请哪些人、达成什么目标', '预计时间、城市与规模'],
    },
    {
      id: 'product-workshops',
      number: '02',
      title: 'AI 产品早期用户 Workshop',
      bestFor: '已经有可用产品，希望听到早期用户反馈或接触中国开发者的 AI 团队',
      description: '产品已经可以试用时，我可以组织小范围 Workshop，邀请开发者和潜在用户体验产品，让团队直接听到使用反馈。',
      outcomes: ['明确这次试用要回答的问题', '邀请愿意试用产品的开发者', '整理使用反馈，供团队决定下一步'],
      invitation: '希望组织一次产品试用和交流？',
      linkLabel: '了解产品 Workshop',
      inquiry: ['产品链接与当前可体验的版本', '这一轮最想验证的问题', '预计时间与希望邀请的用户'],
    },
    {
      id: 'ai-talks',
      number: '03',
      title: 'AI 与 Agent 分享',
      bestFor: '企业、大会、高校与开发者社区',
      description: '我分享自己日常使用 AI、搭建 Agent 和管理多 Agent 系统的经验，具体讲任务怎样分工、怎样检查结果，以及哪些地方容易出错。',
      outcomes: ['主题演讲或圆桌交流', '企业内部分享', '结合工作任务动手的工作坊'],
      invitation: '想邀请我分享 AI 或 Agent 的使用经验？',
      linkLabel: '了解 AI 与 Agent 分享',
      inquiry: ['活动或团队的简单介绍', '听众背景与最关心的问题', '预计时间与分享形式'],
    },
  ],
};
