#!/usr/bin/env python3
"""Rebuild or check the same-source Noto Serif SC subsets. See docs/site-fonts.md."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import tempfile
import unicodedata
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/app/fonts/noto-serif-sc"
COMMIT = "8b0a1d0f5983c89bc2b93f1b5fb55f9e252744b5"
BASE = f"https://raw.githubusercontent.com/google/fonts/{COMMIT}/ofl/notoserifsc/"
SOURCE_FILES = {
    "NotoSerifSC[wght].ttf": "050080d9255a86808f2945bffac582b31ef32bc36411ce29563b4961670c66f9",
    "OFL.txt": "5e0da210fb04058a8c0087985d2d456b931c2579811a49655721d3cf0c36b6d6",
}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def ranges(points):
    result = []
    for point in sorted(points):
        if result and result[-1][1] + 1 == point:
            result[-1][1] = point
        else:
            result.append([point, point])
    return result


def expand(items):
    return {point for start, end in items for point in range(start, end + 1)}


def corpus():
    # Deliberately include all text in public source files: this slightly
    # over-covers comments/code, but cannot miss a title hidden in a component.
    files = sorted(
        path for directory in ("src", "messages", "content")
        for path in (ROOT / directory).rglob("*")
        if path.is_file() and path.suffix in (".ts", ".tsx", ".css", ".json", ".md")
        and OUTPUT not in path.parents
    )
    text = "\n".join(path.read_text() for path in files)
    # Include JS/JSON Unicode escapes used for punctuation and word joiners.
    text += "".join(chr(int(braced or fixed, 16)) for braced, fixed in
                    re.findall(r"\\u(?:\{([0-9a-fA-F]{1,6})\}|([0-9a-fA-F]{4}))", text)
                    if int(braced or fixed, 16) <= 0x10FFFF)
    points = {ord(char) for char in text if not unicodedata.category(char).startswith("C")}
    return points, files


def download(cache, filename, checksum):
    path = cache / filename
    if not path.exists():
        with urllib.request.urlopen(BASE + urllib.parse.quote(filename), timeout=60) as response:
            path.write_bytes(response.read())
    if digest(path) != checksum:
        raise SystemExit(f"Source checksum mismatch: {path}")
    return path


def generate(cache):
    # These optional tools are only needed to regenerate, never for npm build
    # or the offline coverage check. Versions are pinned in the maintenance doc.
    from fontTools import subset
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont

    cache.mkdir(parents=True, exist_ok=True)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    paths = {name: download(cache, name, checksum) for name, checksum in SOURCE_FILES.items()}
    with TTFont(paths["NotoSerifSC[wght].ttf"]) as original:
        available = set(original.getBestCmap())
    needed, _ = corpus()
    selected = (needed | set(range(0x20, 0x100))) & available
    groups = {
        "latin": {point for point in selected if point < 0x2E80},
        "cjk": {point for point in selected if point >= 0x2E80},
    }
    css = ["/* Generated by scripts/site-fonts.py --generate. Do not edit. */"]
    manifest = {"sourceCommit": COMMIT, "sourceFiles": SOURCE_FILES,
                "upstreamCoverage": ranges(available), "subsets": {}}
    for group, points in groups.items():
        font = TTFont(paths["NotoSerifSC[wght].ttf"], recalcTimestamp=False)
        options = subset.Options()
        # Keep fontTools' standard shaping features (kerning, ligatures,
        # language forms, vertical forms), not unused stylistic alternates.
        options.name_IDs = ["*"]
        options.name_legacy = True
        options.name_languages = ["*"]
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        # Preserve exactly the weights previously requested by the site,
        # using one variable face instead of repeating every face 3 times.
        instantiateVariableFont(font, {"wght": (400, 600)}, inplace=True)
        font.flavor = "woff2"
        filename = f"noto-serif-sc-{group}.woff2"
        font.save(OUTPUT / filename)
        coverage = set(font.getBestCmap())
        if points - coverage:
            raise SystemExit(f"Subsetting lost characters in {group}")
        unicode_range = ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}"
                                 for a, b in ranges(coverage))
        css.append(f'''@font-face {{
  font-family: 'Darren Noto Serif SC';
  font-style: normal;
  font-weight: 400 600;
  font-display: swap;
  src: url('./{filename}') format('woff2');
  unicode-range: {unicode_range};
}}''')
        manifest["subsets"][group] = {"file": filename, "bytes": (OUTPUT / filename).stat().st_size,
                                       "sha256": digest(OUTPUT / filename), "coverage": ranges(coverage)}
        font.close()
    css.append('''.site-serif-local {
  --font-site-serif: 'Darren Noto Serif SC', 'Noto Serif SC', 'Songti SC', Georgia, serif;
  /* Resolve this alias on the same element as the local font variable. */
  --font-noto-serif: var(--font-site-serif);
}''')
    (OUTPUT / "fonts.css").write_text("\n\n".join(css) + "\n")
    (OUTPUT / "OFL.txt").write_bytes(paths["OFL.txt"].read_bytes())
    manifest["cssSha256"] = digest(OUTPUT / "fonts.css")
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")


def check():
    manifest = json.loads((OUTPUT / "manifest.json").read_text())
    needed, files = corpus()
    available = expand(manifest["upstreamCoverage"])
    covered = set()
    for group, entry in manifest["subsets"].items():
        path = OUTPUT / entry["file"]
        if digest(path) != entry["sha256"] or path.stat().st_size != entry["bytes"]:
            raise SystemExit(f"Generated asset changed: {path}")
        covered.update(expand(entry["coverage"]))
        print(f"{group}: {entry['bytes']:,} bytes, {len(expand(entry['coverage'])):,} code points")
    if digest(OUTPUT / "OFL.txt") != SOURCE_FILES["OFL.txt"]:
        raise SystemExit("License checksum mismatch")
    if digest(OUTPUT / "fonts.css") != manifest["cssSha256"]:
        raise SystemExit("Generated font CSS changed")
    missing = (needed & available) - covered
    if missing:
        raise SystemExit("Regenerate fonts for new characters: " + "".join(chr(cp) for cp in sorted(missing)))
    fallback = needed - available
    print(f"Coverage OK: {len(files)} source files; {len(needed & available):,} supported characters covered.")
    print("Native fallback (also absent in upstream font): " + " ".join(f"U+{cp:X}" for cp in sorted(fallback)))
    print(f"Font CSS: {(OUTPUT / 'fonts.css').stat().st_size:,} bytes; no network used by this check.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--cache", type=Path, default=Path(tempfile.gettempdir()) / "darren-font-source")
    args = parser.parse_args()
    if args.generate:
        generate(args.cache)
    check()
